Stop build on empty tunnel config

diff --git a/docker-sniproxy/functions b/docker-sniproxy/functions
--- a/docker-sniproxy/functions
+++ b/docker-sniproxy/functions
@@ -20,6 +20,10 @@ function get_tunnel_id() {
 
 function add_tunnel_iface_config() {
     with_backoff $(which curl) --fail https://${1}:${2}@tunnelbroker.net/tunnelInfo.php | sudo tee ${BUILD_ROOT}/tunnelInfo.xml 1>&2
+    if [ ! -f "${BUILD_ROOT}/tunnelInfo.xml" ]; then
+        printf "error obtaining tunnel config, check tunnel broker credentials\n"
+        exit 1
+    fi
     local routed64=$(cat ${BUILD_ROOT}/tunnelInfo.xml | $(which xpath) -q -e "//tunnel[${3}]/routed64/text()" | grep -Po '[a-zA-Z0-9]{1,4}:[a-zA-Z0-9]{1,4}:[a-zA-Z0-9]{1,4}:[a-zA-Z0-9]{1,4}::\/64')
     local serverv4=$(cat ${BUILD_ROOT}/tunnelInfo.xml | $(which xpath) -q -e "//tunnel[${3}]/serverv4/text()" | grep -Po '[0-9]{1,3}+\.[0-9]{1,3}+\.[0-9]{1,3}+\.[0-9]{1,3}')
     local clientv4=$(get_tunnel_clientv4 ${3})
