Aded exponential backoff to tests

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -1,7 +1,10 @@
+# common functions
+
 function get_iface() {
     local iface=$($(which ip) route | grep default | awk '{print $5}')
     echo ${iface}
 }
+
 
 function get_ipaddr() {
     IFACE=$(get_iface)
@@ -13,10 +16,12 @@ function get_ipaddr() {
     echo $(echo ${ipaddr} | awk '{print $1}')
 }
 
+
 function get_ext_ipaddr() {
     local extip=$($(which dig) +short myip.opendns.com @resolver1.opendns.com)
     echo $(echo ${extip} | awk '{print $1}')
 }
+
 
 function get_first_words() {
     local first_words=$(ip -6 addr show dev eth0 scope global | \
@@ -27,10 +32,12 @@ function get_first_words() {
     echo ${first_words}
 }
 
+
 function get_client_ipaddr() {
     local clientip=$(echo ${SSH_CONNECTION} | awk '{print $1}')
     echo ${clientip}
 }
+
 
 function get_last_word() {
     local last_word=$(ip -6 addr show dev eth0 scope global | grep inet6 | awk '{print $2}' | \
@@ -40,10 +47,12 @@ function get_last_word() {
     echo ${last_word}
 }
 
+
 function get_docker_ipv6_subnet() {
     local subnet=$(printf '%s:%x/125\n' $(get_first_words) $((0x$(get_last_word) + 1)))
     echo ${subnet}
 }
+
 
 function ndp_proxy_add_delete () {
     IFACE=$(get_iface)
@@ -54,4 +63,44 @@ function ndp_proxy_add_delete () {
         printf "${1}: proxy ${FIRST_WORDS}:$(printf '%x' $i) dev ${IFACE}\n"
         sudo $(which ip) -6 neigh ${1} proxy ${FIRST_WORDS}:$(printf '%x' $i) dev ${IFACE}
     done
+}
+
+
+# Retries a command a with backoff.
+#
+# The retry count is given by ATTEMPTS (default 5), the
+# initial backoff timeout is given by TIMEOUT in seconds
+# (default 1.)
+#
+# Successive backoffs double the timeout.
+#
+# Beware of set -e killing your whole script!
+function with_backoff {
+  local max_attempts=${ATTEMPTS-5}
+  local timeout=${TIMEOUT-1}
+  local attempt=0
+  local exitCode=0
+
+  while [[ $attempt < $max_attempts ]]
+  do
+    "$@"
+    exitCode=$?
+
+    if [[ $exitCode == 0 ]]
+    then
+      break
+    fi
+
+    echo "Failure! Retrying in $timeout.." 1>&2
+    sleep $timeout
+    attempt=$(( attempt + 1 ))
+    timeout=$(( timeout * 2 ))
+  done
+
+  if [[ $exitCode != 0 ]]
+  then
+    echo "You've failed me for the last time! ($@)" 1>&2
+  fi
+
+  return $exitCode
 }
